package com.combatientes.whismur;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.ImageView;
import android.widget.Toast;

import com.skyfishjy.library.RippleBackground;

import org.json.JSONObject;

import io.chirp.sdk.CallbackCreate;
import io.chirp.sdk.ChirpSDK;
import io.chirp.sdk.model.Chirp;
import io.chirp.sdk.model.ChirpError;

public class Send extends AppCompatActivity {
    Intent intent;
    String message;
    String TAG="Debug";
    JSONObject jsonObject;
    ChirpSDK chirpSDK;
    Context context;
    protected int i= 0;
    static RippleBackground rippleBackground;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_send);
        context=getApplicationContext();
        chirpSDK = new ChirpSDK(context,"ErnLh5hPX7GQGNOnX7OgYrT5N","LshAQXDH3JISYOsRoXlfWKUoAxloskvDpBj9YDG8Vq8xocwFfI");
        rippleBackground=(RippleBackground)findViewById(R.id.content);
        ImageView imageView=(ImageView)findViewById(R.id.centerImage);

        imageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                rippleBackground.stopRippleAnimation();
            }
        });
        try {
            Bundle bundle= getIntent().getExtras();
            message = bundle.getString("message");
            try {

                jsonObject = new JSONObject();
                jsonObject.put("text", message);
                createChirp(jsonObject, message);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    private void createChirp(JSONObject jsonObject, final String sendText)
    {
        /*------------------------------------------------------------------------------
         * Create a chirp encapsulating an arbitrary JSON object.
         * The identifier is generated by the API and returned to the application.
         *----------------------------------------------------------------------------*/
        chirpSDK.create(new Chirp(jsonObject), new CallbackCreate()
        {
            /*------------------------------------------------------------------------------
             * The chirp has been created successfully.
             *----------------------------------------------------------------------------*/
            @Override
            public void onCreateResponse(final Chirp chirp)
            {
                /*------------------------------------------------------------------------------
                 * Play the chirp from the device's speaker.
                 *----------------------------------------------------------------------------*/
                chirpSDK.chirp(chirp);
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        rippleBackground.startRippleAnimation();
                    }
                });
                chirpSDK.start();
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        rippleBackground.stopRippleAnimation();
                    }
                });
                Log.d(TAG, "onCreateResponse: " + chirp.getIdentifier());
                finish();
            }

            @Override
            public void onCreateError(ChirpError chirpError) {
                if (i >= 5) {
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            Toast.makeText(context, "Error encoding data, Try again", Toast.LENGTH_SHORT).show();
                        }
                    });
                Log.d(TAG, "onCreateError: " + chirpError.getMessage());
                finish();
                } else {
                    i++;
                    try {
                        Intent inten = new Intent(getApplicationContext(), Send.class);
                        inten.putExtra("message", sendText);
                        startActivity(inten);
                    }catch (Exception e){
                        Toast.makeText(getApplicationContext(),"Unable to Send",Toast.LENGTH_LONG).show(); ;
                        e.printStackTrace();
                    }
                    finish();
                }
            }
        });

    }

    @Override
    protected void onPause() {
        super.onPause();
        chirpSDK.stop();
    }
}
